apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wordpress
  labels:
    app: {{ .Release.Name }}
    chart: {{ include "wordpress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        tier: frontend
    spec:
      containers:
      - image: {{ .Values.image.wordpress.repository }}:{{ .Values.image.wordpress.tag }}
        name: wordpress
        imagePullPolicy: {{ .Values.image.wordpress.pullPolicy }}
        env:
        - name: WORDPRESS_DB_HOST
          value: {{ .Release.Name }}-mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secret
              key: mysql-password
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secret
              key: mysql-user
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-secret
              key: mysql-database
        ports:
        - containerPort: 80
          name: wordpress
        {{- if .Values.persistence.wordpress.enabled }}
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
        {{- end }}
      {{- if .Values.persistence.wordpress.enabled }}
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-wordpress-pvc
      {{- end }}